uploads = []
outputs = []

[[generated]]
id = "rf7C50_IYKZ7cAx7Szm90"
uri = "file://assets/images/food/plate-hero.png"
type = "image"
title = "premium gourmet food plate"

[[generated]]
id = "yc0pNYDOIpL9WsXIovomX"
uri = "file://assets/images/meals/bb3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YFXl4-QRr7iag9d1xyfVT"
uri = "file://assets/images/meals/bb4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0YtmAL3z-uAxTYyG6Q7i9"
uri = "file://assets/images/meals/fs1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LEIQo_uDlQpr7n6urjjqQ"
uri = "file://assets/images/meals/fs2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NM_7kgBE7FGqcdp48d5GH"
uri = "file://assets/images/meals/fs3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ngBxlskqIldvlG7nv6Gd5"
uri = "file://assets/images/meals/fs4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tNNyVsXzj0aMJ8wUxuBQ-"
uri = "file://assets/images/meals/lt1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jzHxbLErrbHS-zje5G1_1"
uri = "file://assets/images/meals/lt2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xPP-ln8M-mSdu1P4WtvgB"
uri = "file://assets/images/meals/lt3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fF6_RoURF6zkpz9RPsRVr"
uri = "file://assets/images/meals/lt4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "x_6yMWIyMRiEcAySmGFRW"
uri = "file://assets/images/meals/bb1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0BBWlAKSiwlswWEkkZGb0"
uri = "file://assets/images/meals/bb2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vgsKNpxAC8NbVDeQjsvcP"
uri = "file://assets/images/onboarding/welcome-pt.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-WRztmBLXNuB2d9dPGkA0"
uri = "file://assets/images/hero-fitness-es.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PCYncM3oTbMM6_Sz76c6G"
uri = "file://assets/images/hero-fitness-pt.png"
type = "image"
title = "generated_image"

[[generated]]
id = "r8jyllcOrHHmBc0ZouDw_"
uri = "file://assets/images/workouts/workout1-es.png"
type = "image"
title = "generated_image"

[[generated]]
id = "73RMeDlBicRUZE5d1vAxD"
uri = "file://assets/images/workouts/workout2-es.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TYPwtYB8GFWeRKv-3yMV8"
uri = "file://assets/images/workouts/workout3-es.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2djEZZNV_PL2aWhITZWgm"
uri = "file://assets/images/workouts/workout4-es.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Yxlw9eS4QAu2af6d2WkaV"
uri = "file://assets/images/workouts/workout1-pt.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OVPwcuQ4QceK8ib1QCFBZ"
uri = "file://assets/images/workouts/workout2-pt.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dhPg5IIutHDirG5yRMAO7"
uri = "file://assets/images/workouts/workout3-pt.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pdIImfCV8POsNiGSDJ4lH"
uri = "file://assets/images/workouts/workout4-pt.png"
type = "image"
title = "generated_image"

[[generated]]
id = "enfz2QftN8iTEl8YghkwI"
uri = "file://assets/images/onboarding/welcome-es.png"
type = "image"
title = "generated_image"

[[generated]]
id = "r4D55CeqSi7aW8cu4uFPt"
uri = "file://assets/images/progress/before-placeholder.png"
type = "image"
title = "before placeholder"

[[generated]]
id = "mBm4b-k5tuqWacoxerCX3"
uri = "file://assets/images/progress/after-placeholder.png"
type = "image"
title = "after placeholder"
